---
- name: CNI | MASTERS | Copy Calico RBAC
  template:
    src: calico/rbac-kdd.yaml.j2
    dest: "{{ kubeadm_config_dir }}/rbac-kdd.yaml"

- name: CNI | MASTERS | Copy Calico manifest
  template:
    src: calico/calico.yaml.j2
    dest: "{{ kubeadm_config_dir }}/calico.yaml"

- name: CNI | MASTERS | Apply calico manifest
  shell: |
    kubectl apply -f rbac-kdd.yaml
    kubectl apply -f calico.yaml
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
  args:
    chdir: "{{ kubeadm_config_dir }}"
  run_once: yes