---
- hosts: all
  become: true
  gather_facts: false

  roles:
    - bootstrap-os
    - common

- hosts: masters
  become: true
  gather_facts: true
    
- hosts: nodes
  become: true
  gather_facts: true

  roles:
    - kubeadm/node