---

- name: Kubeadm | Node | Check if node already in node list
  shell: |
    kubectl get nodes -o=custom-columns=NAME:.metadata.name --no-headers
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    chdir: "{{ kubeadm_exec_dir }}"
  register: nodes
  delegate_to: "{{ groups['master'] | random(seed=inventory_hostname) }}"
  changed_when: false