---
- name: Kubeadm | Node | Make sure kubeadm dirs exist
  file: path={{ item }} state=directory
  with_items:
    - "{{ kubeadm_config_dirs }}"
    - "{{ nginx_proxy_conf_dir }}"

- name: Kubeadm | Node | Add temporary Iptables rule
  command: sysctl -w net.ipv4.conf.all.route_localnet=1

- name: Kubeadm | Node | Add temporary Iptables rule
  command: iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
    
- name: Kubeadm | Node | Add temporary Iptables rule
  command: iptables -t nat -A OUTPUT -o lo -d 127.0.0.1 -p tcp --dport 6443 -j DNAT  --to-destination {{ hostvars[groups['masters'][0]]['ansible_env']['COREOS_PRIVATE_IPV4'] }}:6443

- name: Kubeadm | DELEGATED TO MASTERS | Generate join token
  shell: kubeadm token create --ttl 5m
  register: kubeadm_token
  delegate_to: "{{ groups['masters'] | random(seed=inventory_hostname) }}"

- name: Kubeadm | Node | Copy kubeadm join config file
  template:
    src: kubeadm-join-config.yml.j2
    dest: "{{ ansible_user_dir }}/kubeadm-join-config.yaml"

- name: Kubeadm | Node | Join cluster
  command: |
    kubeadm join --config kubeadm-join-config.yaml
  args:
    chdir: "{{ ansible_user_dir }}"

- name: kubeadm | DELEGATED TO MASTERS | Mark node role
  command: kubectl label node {{ ansible_fqdn }} kubernetes.io/role=node
  environment:
    KUBECONFIG: '/etc/kubernetes/admin.conf'
  delegate_to: "{{ groups['masters'] | random(seed=inventory_hostname) }}"

- name: Kubeadm | Node | Remove temporary Iptables rule
  command: sysctl -w net.ipv4.conf.all.route_localnet=0

- name: Kubeadm | Node | Remove temporary Iptables rule
  command: iptables -t nat -D POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
    
- name: Kubeadm | Node | Remove temporary Iptables rule
  command: iptables -t nat -D OUTPUT -o lo -d 127.0.0.1 -p tcp --dport 6443 -j DNAT  --to-destination {{ hostvars[groups['masters'][0]]['ansible_env']['COREOS_PRIVATE_IPV4'] }}:6443

- name: Kubeadm | Node | Add nginx-proxy config to manifests
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Kubeadm | Node | Add nginx-proxy file to manifests
  template:
    src: nginx-proxy.yaml.j2
    dest: /etc/kubernetes/manifests/nginx-proxy.yaml